### ISSUE TITLE
Why did you delete your repo?

### ISSUE THREAD

**Issue by KavyanshKhaitan2** [jorgegonzalez/blog#1]
Why did you delete your beginner projects repo? (https://github.com/jorgegonzalez/beginner-projects)
It was great, please bring it back. I saw it on the wayback machine.

**Comment by jorgegonzalez** [comment]
I didn't know people were using it @KavyanshKhaitan2 ... where did you see it?

**Comment by jorgegonzalez** [comment]
https://github.com/jorgegonzalez/beginner-projects revived

**Comment by KavyanshKhaitan2** [comment]
Hey! Thanks, I saw it on reddit, whenever I ask for beginner project ideas
on r/python there is a bot sending the link to the Wayback Machine cause
you deleted it.. if you ever think people are not using something - just
archive it instead!
